### ISSUE TITLE
[EPIC] Cover router

### ISSUE THREAD

**Issue by MilGard91** [NexusMutual/cover-router#8]
# Cover Router

### TODO list
- [ ] Script to fetch StakingPools from StakingPoolFactory
- [ ] Script to fetch StakingPool interactions 
  - [ ] Deposits
  - [ ] Products
  - [ ] Allocation
- [ ] Script to get all Cover interactions
- [ ] Initial Store structure
- [ ] Analyze elements to use for calculating best staking pool for buying cover
- [ ] Write a Calculation for 

### Broader TODO List
- [ ] Create Server
- [ ] Create router
  - [ ] Analyze what data is needed
  - [ ] structure the routes
- [ ] NFT Indexer ?
